lsst-sqre/datalinker

- src/datalinker/main.py
To work around an issue with the current mypy and typeshed, avoid
using get with package metadata.  Get the version using
importlib.metadata.version directly.  We should always have package
metadata available given how we now structure development.
> Update how package metadata is obtained

- requirements/dev.txt
- requirements/main.in
- requirements/main.txt
- src/datalinker/config.py
- src/datalinker/handlers/external.py
- src/datalinker/templates/links.xml
astropy is missing too many features and is too awkward to use to
construct the datalink VOTable.  Use Jinja2 templated XML instead.
Make the links handler non-async since it's calling a bunch of
non-async Butler code under the hood and needs to use a thread
pool.
Add a service_ref row and a resource for the sync version of the
cutout service to the links returned for an image.
> [DM-35001] Add service_ref for cutout service, switch to Jinja2

- README.rst
- src/datalinker/templates/links.xml
Based on CADC practice, the SODA and DALI standards, and a clarification of intent in the DataLink 1.1 draft.  Enables clients to explicitly determine that a param really is intended to be a circle / polygon rather than inferring it.
Required for DP0.2.
> DM-35181: Added DALI xtypes to SODA service descriptors

- README.rst
- requirements/main.in
- src/datalinker/handlers/external.py
- tests/conftest.py
- tests/handlers/external_test.py
- tests/support/butler.py
- tests/support/gcs.py
- tox.ini
- Validate the parameters to cone search and use URL escaping functions
- Support `RESPONSEFORMAT` argument to the links endpoint
- Return 404 errors for invalid IDs instead of partial data
- Return 404 errors for invalid Butler labels
- Validate the id parameter to the links endpoint
- Add a test suite with a mock Butler and mock Google Cloud Storage
- Improve the route annotations for better OpenAPI documentation
- Document the remaining known gaps from the standard
- Minor cleanup here and there
> [DM-35182] Add robustness and a test suite

- src/datalinker/handlers/external.py
- src/datalinker/templates/links.xml
- tests/handlers/external_test.py
- tests/support/butler.py
Raw images aren't supported by the cutout service.  Detect those
with the Butler DatasetRef and exclude the cutout service_ref from
the returned links table.
This is a stopgap solution for DP0.2 until we design a more modular
architecture and decide how much information we want to encode in
the obstap table.
> [DM-35253] Don't return cutout service_ref for raws

- src/datalinker/templates/links.xml
SODA 1.0 errata 1 says that the ID parameter should have type
meta.id;meta.dataset.  This is different than the type of the
exact same parameter in the main links table (meta.id;meta.main),
and I can't find any explanation of why, but it also looks like it
shouldn't matter too much given the discussion in the errata.
Therefore, go with the SODA standard over copying the data type
from the DataLink standard.
> Use meta.id;meta.dataset for SODA ID parameter

- src/datalinker/dependencies/hips.py
- src/datalinker/dependencies/tap.py
- src/datalinker/handlers/external.py
- src/datalinker/handlers/internal.py
- tests/conftest.py
- tests/handlers/internal_test.py
- tests/support/butler.py
Fix the deprecations in PEP 585, and use the | syntax instead of Union and some Optional cases.  Drop unnecessary types from docstrings.
> DM-37516: Update typing and docstrings

- requirements/dev.txt
- requirements/main.in
- requirements/main.txt
- src/datalinker/handlers/external.py
- tests/conftest.py
- tests/handlers/external_test.py
- tests/support/butler.py
Updated usage of the Butler to make it compatible with the new client/server version of Butler.
The biggest change is that we now use a new Butler API 'LabeledButlerFactory' for creating the Butler.  This adds support for RemoteButler, and also fixes some issues when using the old DirectButler.  (The way Datalinker was using a single global Butler shared between threads was never OK -- DirectButler instances are not threadsafe because they have database session state that can get extremely confused if multiple threads use it at the same time.)
Butler server returns signed URLs directly, so there is a new case in the links endpoint that bypasses Datalinker's own URL signing when it gets an HTTP URL from the Butler.
I eliminated usage of some deprecated Butler methods that are not supported …
> DM-42190: Allow use of client/server Butler

- scripts/start-frontend.sh
- src/datalinker/config.py
- src/datalinker/handlers/external.py
Instead of always requiring a file to exist containing the list of Butler repositories, optionally read it from an environment variable.  Equivalent functionality will be added to daf_butler itself shortly, but I don't want to wait another week to get this deployed.
Also fixed a small bug where `unzip` would interactively prompt to overwrite files if the service crashes on startup, preventing you from seeing the error message from the crash in the logs.
> DM-42660: Use Butler repository list from environment var

- changelog.d/20240126_143234_rra_DM_42689.md
- src/datalinker/main.py
If using the production logging profile, also configure Uvicorn logging to use JSON and honor the configured log level.
> DM-42689: Configure Uvicorn logging

- changelog.d/20240126_144524_rra_DM_42689.md
- src/datalinker/config.py
- src/datalinker/handlers/external.py
- src/datalinker/handlers/hips.py
- src/datalinker/handlers/internal.py
- src/datalinker/main.py
Add a configuration parameter for a Slack incoming webhook and, if set, use it to report uncaught exceptions from route handlers.
> DM-42689: Add support for reporting uncaught exceptions

- changelog.d/20240126_145602_rra_DM_42689.md
- src/datalinker/config.py
- src/datalinker/main.py
Support configuration of the DataLink and HiPS URL prefixes on which datalinker should listen.
> DM-42689: Allow URL path prefixes to be configured

- changelog.d/20240126_160310_rra_DM_42689.md
- src/datalinker/config.py
- src/datalinker/dependencies/hips.py
- src/datalinker/dependencies/tap.py
- src/datalinker/handlers/external.py
- tests/conftest.py
- tests/handlers/hips_test.py
- tox.ini
Use a DATALINKER_ prefix for all configuration environment variables and stop using SAFIR_ as a prefix for settings that are passed to Safir. Make mandatory environment variables actually mandatory, and set them to dummy values in tox to avoid issues with the test suite. Declare URLs as HttpUrl so that Pydantic will validate them.
> DM-42689: Tighten configuration settings and validation

- .github/workflows/periodic-ci.yaml
uv refuses to run outside of a virtualenv, so use uv to create one and activate it before running make update-deps. Fix the Python version for running tox in the periodic CI workflow.
> DM-45137: Run make update-deps in a virtualenv

- tests/conftest.py
- tests/handlers/hips_test.py
It's no longer necessary to import types from _pytest. They're all exported by the pytest module now.
> DM-45137: Stop importing from _pytest

- pyproject.toml
Ruff now supports reformatting docstrings, but it's disabled by default. Enable it. Also remove exclusions for some deprecated Ruff diagnostics, since they're no longer enabled by default.
> DM-45137: Enable docstring reformatting

- pyproject.toml
- ruff-shared.toml
- tests/conftest.py
The shared Ruff configuration will be going into the templates once the PR is approved. Switch datalinker over to use an early version of it, and resynchronize it with other packages.
> DM-45137: Switch to a shared Ruff configuration file

- .github/workflows/periodic-ci.yaml
Avoid using always(), since per the GitHub documentation it can cause weird issues. Switch to failure() instead, since we only want to do notifications on failure.
> DM-45137: Fix condition for periodic CI notification

- changelog.d/20240705_171637_rra_DM_45137.md
- src/datalinker/config.py
- src/datalinker/handlers/external.py
- tests/conftest.py
- tests/handlers/external_test.py
Require client/server Butler and remove all of the code for doing our own file upload and URL signing. This massively simplifies the test suite and removes a flaky test with a timing bug. Also drop the configuration settings used only by direct Butler.
> DM-45137: Drop support for direct Butler

- Dockerfile
- scripts/install-base-packages.sh
- scripts/install-dependency-packages.sh
Reduce the stages of the Docker build to three from four, since the additional stage isn't doing much for us. Move git into the install image and out of the base image, since it isn't required after package installation.
> DM-45137: Switch to a three-stage Docker build

- src/datalinker/config.py
- src/datalinker/handlers/external.py
- src/datalinker/main.py
Move the model configuration to the top of `Config` to make it more visible. Drop the explicit handling of `DAF_BUTLER_REPOSITORIES` since this should now be handled internally by the library. Change the type of `slack_webhook` to `SecretStr`.
> DM-48266: Update config, drop explicit Butler repositories

- src/datalinker/models.py
Use `StrEnum` instead of dual inheritance from `str, Enum`, since it does the same thing but more thoroughly.
> DM-48266: Convert to StrEnum

- src/datalinker/handlers/external.py
Use the package loader for Jinja templates instead of file paths, and make sure auto-escaping is enabled.
> DM-48266: Switch to the package loader for Jinja templates

- changelog.d/20241126_213047_steliosvoutsinas_DM_47811.md
Remove the change log for internal FastAPI linter fixes, since this didn't change user-visible behavior.
> DM-48266: Remove unneeded change log

- src/datalinker/main.py
- tests/conftest.py
When iterators are provided by generators, use the more correct `AsyncGenerator` type instead of `AsyncIterator`.
> DM-49067: Switch from AsyncIterator to AsyncGenerator

- pyproject.toml
Update the syntax of the license information in `pyproject.toml` to use PEP 639, and drop the license classifier.
> DM-50042: Adopt PEP 639 license expressions

- pyproject.toml
Add the `Private :: Do Not Upload` classifier to prevent accidental uploads to PyPI.
> DM-50042: Add do-not-upload classifier

- changelog.d/20250411_114846_rra_DM_50042.md
- src/datalinker/config.py
- src/datalinker/handlers/external.py
- tests/handlers/external_test.py
Since the reply to the `{links}` endpoint contains signed URLs with an expiration time, indicate to a client that this reply should only be cached for the lifetime of those links by setting the `Expires` and `Cache-Control` headers (using the `max-age` option of the latter).
> DM-50042: Set Expires and Cache-Control on links replies

- CHANGELOG.md
- Dockerfile
- LICENSE
- changelog.d/20250410_121607_rra_DM_50042.md
- changelog.d/20250411_114846_rra_DM_50042.md
- uv.lock
Collect change log for the 3.2.0 release. Update Python dependencies and bump the minor version of Python used to build containers. Update the copyright date in the LICENSE file.
> DM-50042: Prepare 3.2.0 release

- changelog.d/20250411_142505_rra.md
- src/datalinker/handlers/external.py
- tests/handlers/external_test.py
MDN says that `Expires` is effectively obsolete since HTTP/1.1 given the presence of a `Cache-Control` header with `max-age`, so drop it.
> DM-50042: Drop Expires header from {links} endpoint

- .pre-commit-config.yaml
- changelog.d/20250923_151947_rra_DM_52601.md
- pyproject.toml
- src/datalinker/config.py
- src/datalinker/handlers/external.py
- tests/conftest.py
- tests/data/discovery.json
- tests/handlers/external_test.py
- uv.lock
Use the new FastAPI dependency provided by the rubin-repertoire package and ask Repertoire for the URL for the sync cutout service, rather than requiring explicit configuration. Use the mock provided by rubin-repertoire for testing.
Obtaining the cutout URL had to be moved to a separate dependency from getting the Butler image link, since the Butler client does not have an async interface and thus must run in a non-async handler.
> DM-52601: Use Repertoire to get the cutout sync URL

- tests/conftest.py
- tests/constants.py
Inline the one use into the `app` fixture and remove the constant and `tests/constants.py`.
> DM-52601: Remove TEST_DATA_DIR test constant

- .github/dependabot.yml
- .github/workflows/ci.yaml
- .github/workflows/periodic-ci.yaml
- .pre-commit-config.yaml
- CHANGELOG.md
- Dockerfile
- Makefile
- changelog.d/20250922_134243_rra_DM_52490.md
- changelog.d/20250923_151947_rra_DM_52601.md
- changelog.d/20250923_171313_rra_DM_52601.md
- scripts/update-uv-version.sh
- uv.lock
Collect the change log for the 4.0.0 release and update Python and pre-commit dependencies. Bring datalinker up to date in packaging:
- Pin the uv version in GitHub Actions
- Update the pinned uv version when running `make update`
- Publish versioned Docker images on release instead of on tag
Update the base Docker image to trixie. Clean up some of the change log entries from the previous release that aren't user-facing changes.
> DM-52601: Prepare 4.0.0 release

- changelog.d/20250924_133732_jeremym_DM_52588.md
- src/datalinker/handlers/external.py
- tests/data/columns-principal.yaml
- tests/handlers/external_test.py
This updates the Datalinker so that it supports using the `visit` and `detector` compound key in joins for constructing the time series data. A `join_style` parameter was added which uses the old (DP0.2) style join as the default.
> DM-52588: Add initial implementation of timeseries join on `visit` and `detector`
